### ISSUE TITLE
How can I installed plantiSMASH on our cluster? 

### ISSUE THREAD

**Issue by 2AMissinou** [plantismash/plantismash#3]
Hi dear developer,

I'm Ph.D. student working on Brassica specialized metabolism response to Blackleg & Clubroot in FRANCE. 

Can you help me to install plantiSMASH on your computer cluster and apply it to our data?

Thank you in advance for your help.

**Comment by satriaphd** [comment]
hi, you can try following this guide to install all required packages for plantiSMASH: https://docs.antismash.secondarymetabolites.org/install/#full-manual-install (replace antiSMASH's github cloning to the plantiSMASH one).

If you have any trouble on your way, feel free to send us an e-mail via plantismash@secondarymetabolites.org

**Comment by 2AMissinou** [comment]
Hello my dear,
I am trying to follow your recommendation, but I could not install certain dependencies and the plantiSMASH tool, accepted their download.

I added a file is attached as a follow-up tracks. 
[README-A2M.txt](https://github.com/plantismash/plantismash/files/4576116/README-A2M.txt)


Thanks for your help.
